CREATE TABLE USUARIOS
(
    ID_USUARIO                  VARCHAR (50) NOT NULL,
    USERNAME                    VARCHAR (50) NOT NULL,
    CLAVE_USUARIO               VARCHAR (50) NOT NULL,
    FECHA_CREACION_USU          DATE NOT NULL,
    FECHA_ACTUALIZACION_USU     DATE,
    CODIGO_USUARIO_CREADOR      VARCHAR (50),    
    CODIGO_USUARIO_MODIFICADOR  VARCHAR (50),
    PRIMARY KEY (ID_USUARIO)
);

CREATE UNIQUE INDEX USUARIO_IDX ON USUARIOS(ID_USUARIO);

ALTER TABLE USUARIOS FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE CASCADE;
ALTER TABLE USUARIOS FOREIGN KEY ( CODIGO_USUARIO_MODIFICADOR) REFERENCES USUARIOS ON DELETE CASCADE;


CREATE TABLE CUENTAS
  (
    NUMERO_CUENTA               INTEGER  NOT NULL ,
    FECHA_APERTURA              DATE ,
    SALDO_CUENTA                DECIMAL (10,2) ,
    TIPO_CUENTA                 VARCHAR (100) ,
    FECHA_CREACION_CUENTA       DATE ,
    FECHA_ACTUALIZACION_CUENTA  DATE ,
    CODIGO_USUARIO_CREADOR      VARCHAR (50) NOT NULL ,
    CODIGO_USUARIO_ACTUALIZO    VARCHAR (50),
    PRIMARY KEY (NUMERO_CUENTA)
  ) ;

CREATE UNIQUE INDEX CUENTAS_IDX ON CUENTAS(NUMERO_CUENTA);

ALTER TABLE CUENTAS FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE RESTRICT;
ALTER TABLE CUENTAS FOREIGN KEY ( CODIGO_USUARIO_MODIFICADOR) REFERENCES USUARIOS ON DELETE RESTRICT;

--ALTER TABLE CUENTAS ADD CONSTRAINT CUENTAS_PK PRIMARY KEY ( NUMERO_CUENTA ) ;


CREATE TABLE ABONOS
  (
    CODIGO_DE_ABONO             INTEGER NOT NULL ,
    MONTO                       DECIMAL (10,2) NOT NULL,
    FECHA                       DATE ,
    COMENTARIO                  VARCHAR (200) ,
    NUMERO_CUENTA               INTEGER  NOT NULL ,
    FECHA_CREACION_ABONOS       DATE NOT NULL,
    FECHA_ACTUALIZACION_ABONOS  DATE ,
    CODIGO_USUARIO_CREADOR      VARCHAR (50) NOT NULL ,
    CODIGO_USUARIO_ACTUALIZO    VARCHAR (50) ,
    PRIMARY KEY (CODIGO_DE_ABONO)  
  ) ;

CREATE UNIQUE INDEX ABONO_IDX ON ABONOS(CODIGO_DE_ABONO);

ALTER TABLE ABONOS FOREIGN KEY (NUMERO_CUENTA) REFERENCES CUENTAS ON DELETE RESTRICT;

ALTER TABLE ABONOS FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE RESTRICT;
ALTER TABLE ABONOS FOREIGN KEY ( CODIGO_USUARIO_MODIFICADOR) REFERENCES USUARIOS ON DELETE RESTRICT;

--ALTER TABLE USUARIOS FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE RESTRICT;

CREATE TABLE PRIVILEGIOS
  (
    ID_PRIVILEGIO                  INTEGER NOT NULL ,
    NOMBRE_PRIVILEGIO              VARCHAR (100) ,
    FECHA_CREACION_PRIVILEGIO      DATE ,
    FECHA_ACTUALIZACION_PRIVILEGIO DATE ,
    CODIGO_USUARIO_CREADOR         VARCHAR (50) NOT NULL,
    CODIGO_USUARIO_ACTUALIZO       VARCHAR (50),
    PRIMARY KEY (ID_PRIVILEGIO)
  ) ;

CREATE UNIQUE INDEX PRIVILEGIO_IDX ON PRIVILEGIOS(ID_PRIVILEGIO);

ALTER TABLE PRIVILEGIOS FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE RESTRICT;
ALTER TABLE PRIVILEGIOS FOREIGN KEY ( CODIGO_USUARIO_MODIFICADOR) REFERENCES USUARIOS ON DELETE RESTRICT;

--ALTER TABLE PRIVILEGIOS ADD CONSTRAINT PRIVILEGIOS_PK PRIMARY KEY ( ID_PRIVILEGIO ) ;


CREATE TABLE ROLES
  (
    ID_ROL                   INTEGER NOT NULL ,
    NOMBRE_ROL               VARCHAR (100) ,
    FECHA_CREACION_ROL       DATE ,
    FECHA_ACTUALIZACION_ROL  DATE ,
    CODIGO_USUARIO_CREADOR   VARCHAR (50) NOT NULL ,
    CODIGO_USUARIO_ACTUALIZO VARCHAR (50),
    PRIMARY KEY (ID_ROL)
  ) ;


CREATE UNIQUE INDEX ROL_IDX ON ROLES(ID_ROL);

ALTER TABLE ROLES FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE RESTRICT;
ALTER TABLE ROLES FOREIGN KEY ( CODIGO_USUARIO_MODIFICADOR) REFERENCES USUARIOS ON DELETE RESTRICT;

--ALTER TABLE ROLES ADD CONSTRAINT ROLES_PK PRIMARY KEY ( ID_ROL ) ;


CREATE TABLE ROLES_PRIVILEGIOS
  (
    ID_PRIVILEGIO               INTEGER  NOT NULL ,
    ID_ROL                      INTEGER  NOT NULL ,
    FECHA_CREACION_RP           DATE ,
    FECHA_ACTUALIZACION_RP      DATE ,
    CODIGO_USUARIO_CREADOR      VARCHAR (50) NOT NULL ,
    CODIGO_USUARIO_ACTUALIZO    VARCHAR (50),
    PRIMARY KEY (ID_PRIVILEGIO, ID_ROL)
  ) ;

CREATE UNIQUE INDEX ROL_PRIV_IDX ON ROLES_PRIVILEGIOS(ID_PRIVILEGIO, ID_ROL);

ALTER TABLE ROLES_PRIVILEGIOS FOREIGN KEY (ID_PRIVILEGIO) REFERENCES PRIVILEGIOS ON DELETE RESTRICT;
ALTER TABLE ROLES_PRIVILEGIOS FOREIGN KEY (ID_ROL) REFERENCES ROLES ON DELETE RESTRICT;

ALTER TABLE ROLES_PRIVILEGIOS FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE RESTRICT;
ALTER TABLE ROLES_PRIVILEGIOS FOREIGN KEY ( CODIGO_USUARIO_MODIFICADOR) REFERENCES USUARIOS ON DELETE RESTRICT;

--ALTER TABLE ROLES_PRIVILEGIOS ADD CONSTRAINT ROLES_PRIVILEGIOS_PK PRIMARY KEY ( ID_PRIVILEGIO, ID_ROL ) ;


CREATE TABLE EMPLEADOS
  (
    CODIGO_EMPLEADO              INTEGER NOT NULL ,
    PRIMER_NOMBRE                VARCHAR (20) NOT NULL,
    SEGUNDO_NOMBRE               VARCHAR (20) ,
    PRIMER_APELLIDO              VARCHAR (20) NOT NULL,
    SEGUNDO_APELLIDO             VARCHAR (20) ,
    DIRECCION_CALLE              VARCHAR (20) ,
    DIRECCION_AVENIDA            VARCHAR (20) ,
    DIRECCION_NUM_CASA           INTEGER ,
    DIRECCION_CIUDAD             VARCHAR (30) ,
    DIRECCION_DEPARTAMENTO       VARCHAR (30) ,
    DIRECCION_REFERENCIA         VARCHAR (100) ,
    ID_USUARIO                   VARCHAR (50) NOT NULL,
    EMAIL_SECUNDARIO             VARCHAR (50) ,
    FECHA_NACIMIENTO             DATE ,
    FECHA_INICIO_EN_EMPRESA      DATE NOT NULL,
    FECHA_CREACION_EMPLEADO      DATE NOT NULL,
    FECHA_ACTUALIZACION_EMPLEADO DATE ,
    CODIGO_USUARIO_CREADOR       VARCHAR (50) ,
    CODIGO_USUARIO_ACTUALIZO     VARCHAR (50),
    PRIMARY KEY (CODIGO_EMPLEADO)
  ) ;

CREATE UNIQUE INDEX EMPLEADO_IDX ON EMPLEADOS(CODIGO_EMPLEADO);

ALTER TABLE EMPLEADOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS ON DELETE RESTRICT;

ALTER TABLE EMPLEADOS FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE RESTRICT;
ALTER TABLE EMPLEADOS FOREIGN KEY ( CODIGO_USUARIO_MODIFICADOR) REFERENCES USUARIOS ON DELETE RESTRICT;

--ALTER TABLE EMPLEADOS ADD CONSTRAINT EMPLEADOS_PK PRIMARY KEY ( CODIGO_EMPLEADO ) ;


CREATE TABLE EMPLEADOS_CUENTAS
  (
    CODIGO_EMPLEADO             INTEGER NOT NULL ,
    NUMERO_CUENTA               INTEGER NOT NULL ,
    FECHA_CREACION_EMPC         DATE ,
    FECHA_ACTUALIZACION_EMPC    DATE ,
    CODIGO_USUARIO_CREADOR      VARCHAR (50) NOT NULL ,
    CODIGO_USUARIO_ACTUALIZO    VARCHAR (50),
    PRIMARY KEY (CODIGO_EMPLEADO, NUMERO_CUENTA)
  ) ;

CREATE UNIQUE INDEX EMP_CUENTA_IDX ON EMPLEADOS_CUENTAS(CODIGO_EMPLEADO, NUMERO_CUENTA);

ALTER TABLE EMPLEADOS_CUENTAS FOREIGN KEY (CODIGO_EMPLEADO) REFERENCES EMPLEADOS ON DELETE RESTRICT;
ALTER TABLE EMPLEADOS_CUENTAS FOREIGN KEY (NUMERO_CUENTA) REFERENCES CUENTAS ON DELETE RESTRICT;

ALTER TABLE EMPLEADOS_CUENTAS FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE RESTRICT;
ALTER TABLE EMPLEADOS_CUENTAS FOREIGN KEY ( CODIGO_USUARIO_MODIFICADOR) REFERENCES USUARIOS ON DELETE RESTRICT;

--ALTER TABLE EMPLEADOS_CUENTAS ADD CONSTRAINT EMPLEADOS_CUENTAS_PK PRIMARY KEY ( CODIGO_EMPLEADO, NUMERO_CUENTA ) ;


CREATE TABLE EMPLEADOS_ROLES
  (
    CODIGO_EMPLEADO             INTEGER NOT NULL ,
    ID_ROL                      INTEGER NOT NULL ,
    FECHA_CREACION_ER           DATE ,
    FECHA_ACTUALIZACION_ER      DATE ,
    CODIGO_USUARIO_CREADOR      VARCHAR (50) NOT NULL ,
    CODIGO_USUARIO_ACTUALIZO    VARCHAR (50),
    PRIMARY KEY (CODIGO_EMPLEADO, ID_ROL)
  ) ;

CREATE UNIQUE INDEX EMP_ROL_IDX ON EMPLEADOS_ROLES(CODIGO_EMPLEADO, ID_ROL);

ALTER TABLE EMPLEADOS_ROLES FOREIGN KEY (CODIGO_EMPLEADO) REFERENCES EMPLEADOS ON DELETE RESTRICT;
ALTER TABLE EMPLEADOS_ROLES FOREIGN KEY (ID_ROL) REFERENCES ROLES ON DELETE RESTRICT;

ALTER TABLE EMPLEADOS_ROLES FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE RESTRICT;
ALTER TABLE EMPLEADOS_ROLES FOREIGN KEY ( CODIGO_USUARIO_MODIFICADOR) REFERENCES USUARIOS ON DELETE RESTRICT;

--ALTER TABLE EMPLEADOS_ROLES ADD CONSTRAINT EMPLEADOS_ROLES_PK PRIMARY KEY ( CODIGO_EMPLEADO, ID_ROL ) ;


CREATE TABLE EMPLEADO_TELEFONOS
  (
    CODIGO_EMPLEADO             INTEGER NOT NULL ,
    TELEFONO                    VARCHAR (16) NOT NULL ,
    FECHA_CREACION_ET           DATE ,
    FECHA_ACTUALIZACION_ET      DATE ,
    CODIGO_USUARIO_CREADOR      VARCHAR (50) NOT NULL ,
    CODIGO_USUARIO_ACTUALIZO    VARCHAR (50),
    PRIMARY KEY (CODIGO_EMPLEADO, TELEFONO)
  ) ;

CREATE UNIQUE INDEX EMP_TEL_IDX ON EMPLEADO_TELEFONOS(CODIGO_EMPLEADO, TELEFONO);

ALTER TABLE EMPLEADO_TELEFONOS FOREIGN KEY (CODIGO_EMPLEADO) REFERENCES EMPLEADOS ON DELETE RESTRICT;

ALTER TABLE EMPLEADO_TELEFONOS FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE RESTRICT;
ALTER TABLE EMPLEADO_TELEFONOS FOREIGN KEY ( CODIGO_USUARIO_MODIFICADOR) REFERENCES USUARIOS ON DELETE RESTRICT;

--ALTER TABLE EMPLEADO_TELEFONOS ADD CONSTRAINT EMPLEADO_TELEFONOS_PK PRIMARY KEY ( CODIGO_EMPLEADO, TELEFONO ) ;


CREATE TABLE PERSONA_EXTERNA
  (
    CODIGO_PERSONA               INTEGER NOT NULL ,
    PRIMER_NOMBRE                VARCHAR (20) ,
    SEGUNDO_NOMBRE               VARCHAR (20) ,
    PRIMER_APELLIDO              VARCHAR (20) ,
    SEGUNDO_APELLIDO             VARCHAR (20) ,
    DIRECCION_CALLE              VARCHAR (20) ,
    DIRECCION_AVENIDA            VARCHAR (20) ,
    DIRECCION_NUM_CASA           INTEGER (6) ,
    DIRECCION_CIUDAD             VARCHAR (30) ,
    DIRECCION_DEPARTAMENTO       VARCHAR (30) ,
    DIRECCION_REFERENCIA         VARCHAR (100) ,
    EMAIL_PRIMARIO               VARCHAR (50) ,
    EMAIL_SECUNDARIO             VARCHAR (50) ,
    FECHA_NACIMIENTO             DATE ,
    FECHA_CREACION_PERSONA       DATE ,
    FECHA_ACTUALIZACION_PERSONA  DATE ,
    CODIGO_USUARIO_CREADOR       VARCHAR (50) NOT NULL ,
    CODIGO_USUARIO_ACTUALIZACION VARCHAR (50),
    PRIMARY KEY (CODIGO_PERSONA)
  ) ;

CREATE UNIQUE INDEX PERSONA_IDX ON PERSONA_EXTERNA(CODIGO_PERSONA);

ALTER TABLE PERSONA_EXTERNA FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE RESTRICT;
ALTER TABLE PERSONA_EXTERNA FOREIGN KEY ( CODIGO_USUARIO_MODIFICADOR) REFERENCES USUARIOS ON DELETE RESTRICT;

--ALTER TABLE PERSONA_EXTERNA ADD CONSTRAINT PERSONA_EXTERNA_PK PRIMARY KEY ( CODIGO_PERSONA ) ;


CREATE TABLE PERSONA_TELEFONOS
  (
    CODIGO_PERSONA           INTEGER NOT NULL ,
    TELEFONO                 VARCHAR (16) NOT NULL ,
    FECHA_CREACION_ET        DATE ,
    FECHA_ACTUALIZACION_ET   DATE ,
    CODIGO_USUARIO_CREADOR   VARCHAR (50) NOT NULL ,
    CODIGO_USUARIO_ACTUALIZO VARCHAR (50),
    PRIMARY KEY (CODIGO_PERSONA, TELEFONO)
  ) ;

CREATE UNIQUE INDEX PER_TEL_IDX ON PERSONA_TELEFONOS(CODIGO_PERSONA, TELEFONO);

ALTER TABLE PERSONA_TELEFONOS FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE RESTRICT;
ALTER TABLE PERSONA_TELEFONOS FOREIGN KEY ( CODIGO_USUARIO_MODIFICADOR) REFERENCES USUARIOS ON DELETE RESTRICT;

----------------------

CREATE TABLE PRESTAMOS
  (
    NUMERO_PRESTAMO                INTEGER NOT NULL ,
    FECHA_PRESTAMO                 DATE NOT NULL ,
    MONTO_PRESTAMO                 DECIMAL (10,2) NOT NULL ,
    PERIODOS                       INTEGER (2) NOT NULL ,
    SALDO                          INTEGER (10,2) NOT NULL ,
    CODIGO_EMPLEADO                INTEGER (8) NOT NULL ,
    CODIGO_PERSONA                 INTEGER (8) NOT NULL ,
    CODIGO_PERSONA_AVAL            INTEGER (8) NOT NULL ,
    PARENTESCO_AVAL                VARCHAR (100) ,
    FECHA_CREACION_PRESTAMO        DATE ,
    FECHA_ACTUALIZACION_PRESTAMO   DATE ,
    CODIGO_USUARIO_CREADOR         VARCHAR (50) NOT NULL ,
    CODIGO_USUARIO_ACTUALIZO       VARCHAR (50)
  ) ;

CREATE UNIQUE INDEX PRESTAMO_IDX ON PRESTAMOS(NUMERO_PRESTAMO);

ALTER TABLE PRESTAMOS FOREIGN KEY (CODIGO_EMPLEADO) REFERENCES EMPLEADOS ON DELETE RESTRICT;
ALTER TABLE PRESTAMOS FOREIGN KEY (CODIGO_PERSONA) REFERENCES PERSONA_EXTERNA ON DELETE RESTRICT;
ALTER TABLE PRESTAMOS FOREIGN KEY (CODIGO_PERSONA_AVAL) REFERENCES EMPLEADOS ON DELETE RESTRICT;

ALTER TABLE PRESTAMOS FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE RESTRICT;
ALTER TABLE PRESTAMOS FOREIGN KEY ( CODIGO_USUARIO_MODIFICADOR) REFERENCES USUARIOS ON DELETE RESTRICT;

--ALTER TABLE PRESTAMOS ADD CONSTRAINT PRESTAMOS_PK PRIMARY KEY ( NUMERO_PRESTAMO ) ;

CREATE TABLE PAGOS
  (
    NUMERO_PRESTAMO             INTEGER NOT NULL ,
    NUMERO_PAGO                 INTEGER (8) NOT NULL ,
    FECHA_PAGO                  DATE ,
    MONTO_PAGO                  DECIMAL (10,2) ,
    FECHA_CREACION_PAGO         DATE ,
    FECHA_ACTUALIZACION_PAGO    DATE ,
    CODIGO_USUARIO_CREADOR      VARCHAR (50) NOT NULL ,
    CODIGO_USUARIO_ACTUALIZO    VARCHAR (50),
    PRIMARY KEY (NUMERO_PRESTAMO, NUMERO_PAGO)
  ) ;

CREATE UNIQUE INDEX PAGO_IDX ON PAGOS(NUMERO_PRESTAMO, NUMERO_PAGO);

ALTER TABLE PAGOS FOREIGN KEY (NUMERO_PRESTAMO) REFERENCES PRESTAMOS ON DELETE RESTRICT;

ALTER TABLE PERSONA_EXTERNA FOREIGN KEY ( CODIGO_USUARIO_CREADOR) REFERENCES USUARIOS ON DELETE RESTRICT;
ALTER TABLE PERSONA_EXTERNA FOREIGN KEY ( CODIGO_USUARIO_MODIFICADOR) REFERENCES USUARIOS ON DELETE RESTRICT;

--ALTER TABLE PAGOS ADD CONSTRAINT PAGOS_PK PRIMARY KEY ( NUMERO_PAGO, NUMERO_PRESTAMO ) ;

--constraints
/*
ALTER TABLE ABONOS ADD CONSTRAINT ABONOS_CUENTAS_FK FOREIGN KEY ( NUMERO_CUENTA ) REFERENCES CUENTAS ( NUMERO_CUENTA ) ;

ALTER TABLE ABONOS ADD CONSTRAINT ABONOS_USERA_FK FOREIGN KEY ( CODIGO_USUARIO_ACTUALIZO ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE ABONOS ADD CONSTRAINT ABONOS_USERC_FK FOREIGN KEY ( CODIGO_USUARIO_CREADOR ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE CUENTAS ADD CONSTRAINT CUENTAS_USERA_FK FOREIGN KEY ( CODIGO_USUARIO_ACTUALIZO ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE CUENTAS ADD CONSTRAINT CUENTAS_USERC_FK FOREIGN KEY ( CODIGO_USUARIO_CREADOR ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE EMPLEADOS_CUENTAS ADD CONSTRAINT EC_CUENTAS_FK FOREIGN KEY ( NUMERO_CUENTA ) REFERENCES CUENTAS ( NUMERO_CUENTA ) ;

ALTER TABLE EMPLEADOS_CUENTAS ADD CONSTRAINT EC_EMPLEADOS_FK FOREIGN KEY ( CODIGO_PERSONA ) REFERENCES EMPLEADOS ( CODIGO_PERSONA ) ;

ALTER TABLE EMPLEADOS_CUENTAS ADD CONSTRAINT EC_USERA_FK FOREIGN KEY ( CODIGO_USUARIO_ACTUALIZO ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE EMPLEADOS_CUENTAS ADD CONSTRAINT EC_USERC_FK FOREIGN KEY ( CODIGO_USUARIO_CREADOR ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE EMPLEADOS_ROLES ADD CONSTRAINT ER_EMPLEADOS_FK FOREIGN KEY ( CODIGO_EMPLEADO ) REFERENCES EMPLEADOS ( CODIGO_EMPLEADO ) ;

ALTER TABLE EMPLEADOS_ROLES ADD CONSTRAINT ER_ROLES_FK FOREIGN KEY ( ID_ROL ) REFERENCES ROLES ( ID_ROL ) ;

ALTER TABLE EMPLEADOS_ROLES ADD CONSTRAINT ER_USERA_EMPLEADOS_FK FOREIGN KEY ( CODIGO_USUARIO_ACTUALIZO ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE EMPLEADOS_ROLES ADD CONSTRAINT ER_USERC_EMPLEADOS_FK FOREIGN KEY ( CODIGO_USUARIO_CREADOR ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE EMPLEADO_TELEFONOS ADD CONSTRAINT ET_EMPLEADOS_FK FOREIGN KEY ( CODIGO_EMPLEADO ) REFERENCES EMPLEADOS ( CODIGO_EMPLEADO ) ;

ALTER TABLE EMPLEADO_TELEFONOS ADD CONSTRAINT ET_USERA_FK FOREIGN KEY ( CODIGO_USUARIO_ACTUALIZO ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE EMPLEADO_TELEFONOS ADD CONSTRAINT ET_USERC_FK FOREIGN KEY ( CODIGO_USUARIO_CREADOR ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE PAGOS ADD CONSTRAINT PAGOS_PRESTAMOS_FK FOREIGN KEY ( NUMERO_PRESTAMO ) REFERENCES PRESTAMOS ( NUMERO_PRESTAMO ) ;

ALTER TABLE PAGOS ADD CONSTRAINT PAGOS_USERA_FK FOREIGN KEY ( CODIGO_USUARIO_ACTUALIZO ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE PAGOS ADD CONSTRAINT PAGOS_USERC_FK FOREIGN KEY ( CODIGO_USUARIO_CREADOR ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE PERSONA_EXTERNA ADD CONSTRAINT PERSONA_EXTERNA_USERA_FK FOREIGN KEY ( CODIGO_USUARIO_ACTUALIZACION ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE PERSONA_EXTERNA ADD CONSTRAINT PERSONA_EXTERNA_USERC_FK FOREIGN KEY ( CODIGO_USUARIO_CREADOR ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE PRESTAMOS ADD CONSTRAINT PRESTAMOS_EMPLEADOS_FK FOREIGN KEY ( CODIGO_EMPLEADO ) REFERENCES EMPLEADOS ( CODIGO_EMPLEADO ) ;

ALTER TABLE PRESTAMOS ADD CONSTRAINT PRESTAMOS_EMPLEADOS_FKv1 FOREIGN KEY ( CODIGO_PERSONA_AVAL ) REFERENCES EMPLEADOS ( CODIGO_EMPLEADO ) ;

ALTER TABLE PRESTAMOS ADD CONSTRAINT PRESTAMOS_PERSONA_EXTERNA_FK FOREIGN KEY ( CODIGO_PERSONA ) REFERENCES PERSONA_EXTERNA ( CODIGO_PERSONA ) ;

ALTER TABLE PRESTAMOS ADD CONSTRAINT PRESTAMOS_USERA_FK FOREIGN KEY ( CODIGO_USUARIO_ACTUALIZO ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE PRESTAMOS ADD CONSTRAINT PRESTAMOS_USERC_FK FOREIGN KEY ( CODIGO_USUARIO_CREADOR ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE PRIVILEGIOS ADD CONSTRAINT PRIVILEGIOS_USERA_FK FOREIGN KEY ( CODIGO_USUARIO_ACTUALIZO ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE PRIVILEGIOS ADD CONSTRAINT PRIVILEGIOS_USERC_FK FOREIGN KEY ( CODIGO_USUARIO_CREADOR ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE ROLES ADD CONSTRAINT ROLES_USERC_FK FOREIGN KEY ( CODIGO_USUARIO_CREADOR ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE ROLES ADD CONSTRAINT ROLES_USER_FK FOREIGN KEY ( CODIGO_USUARIO_ACTUALIZO ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE ROLES_PRIVILEGIOS ADD CONSTRAINT RP_PRIVILEGIOS_FK FOREIGN KEY ( ID_PRIVILEGIO ) REFERENCES PRIVILEGIOS ( ID_PRIVILEGIO ) ;

ALTER TABLE ROLES_PRIVILEGIOS ADD CONSTRAINT RP_ROLES_FK FOREIGN KEY ( ID_ROL ) REFERENCES ROLES ( ID_ROL ) ;

ALTER TABLE ROLES_PRIVILEGIOS ADD CONSTRAINT RP_USERA_FK FOREIGN KEY ( CODIGO_USUARIO_ACTUALIZO ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE ROLES_PRIVILEGIOS ADD CONSTRAINT RP_USERC_FK FOREIGN KEY ( CODIGO_USUARIO_CREADOR ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE EMPLEADOS ADD CONSTRAINT USERA_EMPLEADOS_FK FOREIGN KEY ( CODIGO_USUARIO_ACTUALIZO ) REFERENCES USUARIOS ( ID_USUARIO ) ;

ALTER TABLE EMPLEADOS ADD CONSTRAINT USERC_EMPLEADOS_FK FOREIGN KEY ( CODIGO_USUARIO_CREADOR ) REFERENCES USUARIOS ( ID_USUARIO ) ;
*/