package View;

import Model.ModelUsuarios;
import Controller.CUsuarios;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Raim
 */
public class Usuarios extends javax.swing.JInternalFrame {

    ModelUsuarios m = new ModelUsuarios();
    CUsuarios c = new CUsuarios();

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tClave = new javax.swing.JTextField();
        nuevojB = new javax.swing.JButton();
        guardarjB = new javax.swing.JButton();
        modificarjB = new javax.swing.JButton();
        eliminarjB = new javax.swing.JButton();
        salirjB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tIdUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsers = new javax.swing.JTable();
        cargar = new javax.swing.JButton();

        jLabel3.setText("Clave:");

        nuevojB.setText("Nuevo");
        nuevojB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevojBActionPerformed(evt);
            }
        });

        guardarjB.setText("Guardar");
        guardarjB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarjBActionPerformed(evt);
            }
        });

        modificarjB.setText("Modificar");
        modificarjB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarjBActionPerformed(evt);
            }
        });

        eliminarjB.setText("Eliminar");
        eliminarjB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarjBActionPerformed(evt);
            }
        });

        salirjB.setText("Salir");
        salirjB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirjBActionPerformed(evt);
            }
        });

        jLabel1.setText("Id Usuario:");

        tIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Username:");

        tablaUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
            },
            new String [] {
                "Id Usuario", "Username", "Clave", "Fecha Creacion",
                "Fecha Actualizacion", "Usuario Creador", "Usuario Actualizador"
            }
        ));
        jScrollPane1.setViewportView(tablaUsers);

        cargar.setLabel("Cargar");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tClave, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevojB)
                        .addGap(27, 27, 27)
                        .addComponent(guardarjB)
                        .addGap(26, 26, 26)
                        .addComponent(modificarjB)
                        .addGap(19, 19, 19)
                        .addComponent(eliminarjB)
                        .addGap(18, 18, 18)
                        .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salirjB)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevojB)
                    .addComponent(guardarjB)
                    .addComponent(modificarjB)
                    .addComponent(eliminarjB)
                    .addComponent(salirjB)
                    .addComponent(cargar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Limpiar() {
        tIdUsuario.setText("");
        tUsername.setText("");
        tClave.setText("");
    }

    private void nuevojBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevojBActionPerformed
        Limpiar();
        modificarjB.setEnabled(false);
        tIdUsuario.setEnabled(true);
        tIdUsuario.grabFocus();
    }//GEN-LAST:event_nuevojBActionPerformed

    private void guardarjBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarjBActionPerformed
        m.idUsuario = (tIdUsuario.getText());
        m.username = (tUsername.getText());
        m.claveUsuario = (tClave.getText());
        m.usuarioCreador = m.idUsuario;
        c.insertUsuarios(m);

        JOptionPane.showMessageDialog(null, "Registro guardado.");
        tIdUsuario.setEnabled(true);
        modificarjB.setEnabled(true);
        Limpiar();
    }//GEN-LAST:event_guardarjBActionPerformed

    private void modificarjBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarjBActionPerformed
        /*MEmpleados m = new MEmpleados();
         m.setEmpleadoID(Integer.parseInt(CodigojT.getText()));
         m.setNombre(nombrejT.getText());
         m.setIdentidad(identidadjT.getText());
         m.setSexo(sexojT.getText());

         c.updateEmpleados(m);
         JOptionPane.showMessageDialog(null, "Registro actualizado");
         modificarjB.setEnabled(true);
         Limpiar();*/
    }//GEN-LAST:event_modificarjBActionPerformed

    private void eliminarjBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarjBActionPerformed
        /*c.deleteEmpleados(Integer.parseInt(CodigojT.getText()));
         JOptionPane.showMessageDialog(null, "Registro eliminado.");
         CodigojT.setEnabled(true);
         modificarjB.setEnabled(true);
         Limpiar();*/
    }//GEN-LAST:event_eliminarjBActionPerformed

    private void salirjBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirjBActionPerformed
        dispose();
    }//GEN-LAST:event_salirjBActionPerformed

    private void tIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdUsuarioActionPerformed
        /*m = c.getEmpleados(Integer.parseInt(evt.getActionCommand()));
         nombrejT.setText(m.getNombre());
         identidadjT.setText(m.getIdentidad());
         sexojT.setText(m.getSexo());
         */
    }//GEN-LAST:event_tIdUsuarioActionPerformed

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        DefaultListModel l = c.obtenerDatos();

        Object[] objetos = l.toArray();

        DefaultTableModel m = new DefaultTableModel();
        try {

            for (int i = 0; i < objetos.length; i += 7) {
                Object[] data = {objetos[i], objetos[i + 1], objetos[i + 2], objetos[i + 3], objetos[i + 4], objetos[i + 5], objetos[i + 6]};
                m.addRow(data);
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        tablaUsers.setModel(m);
    }//GEN-LAST:event_cargarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargar;
    private javax.swing.JButton eliminarjB;
    private javax.swing.JButton guardarjB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarjB;
    private javax.swing.JButton nuevojB;
    private javax.swing.JButton salirjB;
    private javax.swing.JTextField tClave;
    private javax.swing.JTextField tIdUsuario;
    private javax.swing.JTextField tUsername;
    private javax.swing.JTable tablaUsers;
    // End of variables declaration//GEN-END:variables
}
